### ISSUE TITLE
Confirmation when data export is complete

### ISSUE THREAD

**Issue by brianfunk3** [brianfunk3/PIEthon#12]
Either a pop up or just text in the GUI window

**Comment by brianfunk3** [comment]
Would be good to just close the data preview window actually, and then to update status at bottom of mainWindow

**Comment by tuck826** [comment]
I have been trying to fox this issue with a label which we talked about. I have been looking at the main and comparing labels and what needs to be down but honestly cannot figure it out. Would like to walk through this with you at some point

**Comment by brianfunk3** [comment]
It'd actually be nice to get a 'close' button on the this GUI as well, which would help in organizing things. Maybe move close and export button into an hbox that sits below the main stuff in the window, and then we could add the status label below it. Lemme know what questions you have about this @tuck826 next time I see ya

**Comment by brianfunk3** [comment]
implemented with preview gui .5 overhaul
