### ISSUE TITLE
Document process of developing on PIEthon

### ISSUE THREAD

**Issue by brianfunk3** [brianfunk3/PIEthon#38]
Basically just write out all the info you just got out of today. I the idea is that someone new can look at this and start working an knowing what to do

Installing PIEthon, talking to Brian to request access to the Github, finding issues and assigning them/commenting, creating your own branch and working from it, git clone, add commit, push stuff.

**Comment by tuck826** [comment]
Finished and uploaded to the box. Suggestion - make a README.md and make it the PIEthon documentation when you finished updating it.
